import type { DriverLang } from './driver-settings';

const en = {
  tabHome: 'Home',
  tabTrip: 'Trip',
  tabHistory: 'History',
  tabAlerts: 'Alerts',
  tabAccount: 'Account',
  online: 'Online',
  offline: 'Offline',
  todayEarnings: "Today's earnings",
  delivered: 'Delivered',
  active: 'Active',
  avgPerOrder: 'Avg / order',
  allTime: 'All time',
  orders: 'orders',
  lookingForOrders: 'Looking for nearby orders',
  goOffline: 'Go offline',
  updating: 'Updating...',
  start: 'GO',
  youAreOffline: 'You are offline',
  tapGoToReceive: 'Tap GO to receive orders.',
  ordersWillAppear: 'New orders will appear here.',
  orderInProgress: 'You have an active order.',
  verificationReview: 'Admin is reviewing your details.',
  verificationRejected: 'Verification was rejected. Update your profile.',
  payToReceive: 'Pay to receive orders.',
  paymentPending: 'Payment pending. Confirm on your phone.',
  newOrder: 'New order',
  pickup: 'Pickup',
  dropoff: 'Drop-off',
  accept: 'ACCEPT',
  accepting: 'Accepting...',
  decline: 'Decline',
  declining: 'Declining...',
  navigate: 'Navigate',
  cancelTrip: 'Cancel trip',
  cancelling: 'Cancelling...',
  atPickup: 'At pickup',
  onTrip: 'On trip',
  deliveredStatus: 'Delivered',
  waitingOrder: 'Waiting',
  noActiveTrip: 'No active trip',
  noActiveTripHint: 'Go online and wait for the next delivery.',
  activeDelivery: 'Active delivery',
  tripRoute: 'Route',
  customerChat: 'Chat',
  messageCustomer: 'Message the customer',
  send: 'Send',
  sending: 'Sending...',
  openNavigation: 'Navigate',
  callCustomer: 'Call',
  refreshLocation: 'Refresh location',
  rejectOrder: 'Decline',
  historyTitle: 'History',
  historySubtitle: 'Completed and active deliveries.',
  jobs: 'jobs',
  earnings: 'Earnings',
  rateCustomer: 'Rate customer',
  saveRating: 'Save rating',
  savingRating: 'Saving...',
  tripRecords: 'Trips',
  noHistory: 'No trips yet',
  noHistoryHint: 'Completed deliveries will show up here.',
  alertsTitle: 'Alerts',
  alertsClear: 'All clear',
  alertsLive: 'live alerts',
  alertsSubtitle: 'Trip, payment, and dispatch updates.',
  noAlerts: 'No alerts right now',
  noAlertsHint: 'Dispatch and trip updates will appear here.',
  driverAccount: 'Driver account',
  settings: 'Settings',
  settingsSubtitle: 'Language and trip preferences.',
  language: 'Language',
  languageEnglish: 'English',
  languageSwahili: 'Kiswahili',
  autoConfirm: 'Auto-confirm orders',
  autoConfirmHint: 'Accept new jobs automatically when they are assigned.',
  profile: 'Profile',
  phoneNumber: 'Phone number',
  vehicle: 'Vehicle',
  plateNumber: 'Plate number',
  liveLocation: 'Live location',
  locationActive: 'Active',
  locationNeedsAccess: 'Needs access',
  notSet: 'Not set',
  accountControls: 'Account',
  goOnline: 'Go online',
  goOfflineLong: 'Go offline',
  signOut: 'Sign out',
  signingOut: 'Signing out...',
  payNow: 'Pay now',
  pending: 'Pending',
  free: 'Free',
  ready: 'Ready',
  hold: 'Hold',
  due: 'Due',
  clear: 'Clear',
};

const sw: typeof en = {
  tabHome: 'Nyumbani',
  tabTrip: 'Safari',
  tabHistory: 'Historia',
  tabAlerts: 'Arifa',
  tabAccount: 'Akaunti',
  online: 'Mtandaoni',
  offline: 'Nje ya mtandao',
  todayEarnings: 'Mapato ya leo',
  delivered: 'Imeletwa',
  active: 'Zinazoendelea',
  avgPerOrder: 'Wastani / oda',
  allTime: 'Jumla yote',
  orders: 'oda',
  lookingForOrders: 'Inatafuta oda karibu',
  goOffline: 'Toka mtandaoni',
  updating: 'Inasasisha...',
  start: 'ANZA',
  youAreOffline: 'Uko nje ya mtandao',
  tapGoToReceive: 'Bofya ANZA ili upokee oda.',
  ordersWillAppear: 'Oda zitaonekana hapa.',
  orderInProgress: 'Una oda inayoendelea sasa.',
  verificationReview: 'Admin anapitia taarifa zako.',
  verificationRejected: 'Uthibitisho umekataliwa. Sasisha taarifa zako.',
  payToReceive: 'Lipa ili upokee oda.',
  paymentPending: 'Malipo yanasubiri. Thibitisha kwenye simu.',
  newOrder: 'Oda mpya',
  pickup: 'Chukua',
  dropoff: 'Fikisha',
  accept: 'POKEA',
  accepting: 'Inapokea...',
  decline: 'Kataa',
  declining: 'Inakataa...',
  navigate: 'Ramani',
  cancelTrip: 'Ghairi safari',
  cancelling: 'Inaghairi...',
  atPickup: 'Uko pickup',
  onTrip: 'Safari inaendelea',
  deliveredStatus: 'Imewasilishwa',
  waitingOrder: 'Inasubiri',
  noActiveTrip: 'Hakuna safari sasa',
  noActiveTripHint: 'Nenda mtandaoni na subiri oda.',
  activeDelivery: 'Safari inayoendelea',
  tripRoute: 'Njia',
  customerChat: 'Chat',
  messageCustomer: 'Andika ujumbe',
  send: 'Tuma',
  sending: 'Inatuma...',
  openNavigation: 'Ramani',
  callCustomer: 'Piga',
  refreshLocation: 'Sasisha eneo',
  rejectOrder: 'Kataa',
  historyTitle: 'Historia',
  historySubtitle: 'Oda zilizokamilika na zinazoendelea.',
  jobs: 'oda',
  earnings: 'Mapato',
  rateCustomer: 'Kadiria mteja',
  saveRating: 'Hifadhi',
  savingRating: 'Inahifadhi...',
  tripRecords: 'Safari',
  noHistory: 'Bado hakuna safari',
  noHistoryHint: 'Oda zilizokamilika zitaonekana hapa.',
  alertsTitle: 'Arifa',
  alertsClear: 'Hakuna arifa',
  alertsLive: 'arifa',
  alertsSubtitle: 'Taarifa za safari, malipo, na dispatch.',
  noAlerts: 'Hakuna arifa sasa',
  noAlertsHint: 'Taarifa za oda zitaonekana hapa.',
  driverAccount: 'Akaunti ya dereva',
  settings: 'Mipangilio',
  settingsSubtitle: 'Lugha na mapendeleo ya oda.',
  language: 'Lugha',
  languageEnglish: 'English',
  languageSwahili: 'Kiswahili',
  autoConfirm: 'Pokea oda kiotomatiki',
  autoConfirmHint: 'Oda mpya zitakubaliwa peke yake zinapopewa.',
  profile: 'Wasifu',
  phoneNumber: 'Namba ya simu',
  vehicle: 'Gari',
  plateNumber: 'Namba ya plat',
  liveLocation: 'Eneo hai',
  locationActive: 'Imewashwa',
  locationNeedsAccess: 'Inahitaji ruhusa',
  notSet: 'Haijawekwa',
  accountControls: 'Akaunti',
  goOnline: 'Nenda mtandaoni',
  goOfflineLong: 'Toka mtandaoni',
  signOut: 'Toka',
  signingOut: 'Inatoka...',
  payNow: 'Lipa sasa',
  pending: 'Inasubiri',
  free: 'Bure',
  ready: 'Tayari',
  hold: 'Simama',
  due: 'Inadaiwa',
  clear: 'Safi',
};

export type DriverCopy = typeof en;

export function getDriverCopy(language: DriverLang): DriverCopy {
  return language === 'sw' ? sw : en;
}
