import { useLanguage } from '@/providers/language-provider';

const en = {
  nav: {
    home: 'Home',
    track: 'Track',
    history: 'History',
    account: 'Account',
  },
  common: {
    continue: 'Continue',
    from: 'From',
    to: 'To',
    change: 'Change',
    login: 'Login',
    register: 'Register',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    notNow: 'Not now',
    gotIt: 'Got it',
  },
  notice: {
    offlineTitle: "You're offline",
    offlineText: 'Connect to the internet to search places and continue.',
    locationTitle: "We couldn't find that place",
    locationText: 'Try a nearby street, area, or landmark.',
    serviceTitle: 'Place search is temporarily unavailable',
    serviceText: 'Please try again in a few seconds.',
  },
  login: {
    title: 'Login',
    email: 'Email',
    password: 'Password',
    submit: 'Login',
    submitting: 'Logging in...',
    missing: 'Enter your email and password.',
    forgot: 'Forgot password?',
    noAccount: 'No account?',
    legal: 'By continuing, you agree to the',
    terms: 'Terms',
  },
  register: {
    title: 'Register',
    fullName: 'Full name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    submit: 'Register',
    submitting: 'Creating account...',
    missing: 'Fill in full name, phone, email and password.',
    invalidPhone: 'Enter a valid phone number.',
    shortPassword: 'Password must have at least 6 characters.',
    mismatch: 'Passwords do not match.',
    termsRequired: 'Agree to the Terms and Privacy Policy to continue.',
    agree: 'I agree to the',
    terms: 'Terms',
    and: 'and',
    privacy: 'Privacy Policy',
    haveAccount: 'Already have an account?',
  },
  menu: {
    title: 'Menu',
    notSignedIn: 'Not signed in',
    signOut: 'Sign out',
    signOutFailed: 'Sign out failed',
    tryAgain: 'Please try again.',
    account: 'Account',
    savedPlaces: 'Saved places',
    notifications: 'Notifications',
    help: 'Help',
    policies: 'Policies',
  },
  help: {
    title: 'Help',
    intro: 'Call or message us if you need help with an order.',
    call: 'Call',
    whatsapp: 'WhatsApp',
    policies: 'Policies',
    callFailed: 'Unable to call',
    callHint: 'Please call {phone} directly.',
    whatsappFailed: 'Unable to open WhatsApp',
    whatsappHint: 'Please message {phone} on WhatsApp.',
  },
  notifications: {
    title: 'Notifications',
    enable: 'Turn on alerts for order updates',
    opening: 'Opening settings...',
    emptyTitle: 'No notifications',
    emptyText: 'Order updates will appear here.',
    updates: 'updates',
    update: 'update',
    clearAll: 'Clear all',
    deleting: 'Deleting...',
  },
  savedPlaces: {
    title: 'Saved places',
    home: 'Home',
    office: 'Office',
    shop: 'Shop',
    other: 'Other',
    placeName: 'Place name',
    address: 'Address or landmark',
    yourPlaces: 'Your places',
    empty: 'No saved places yet.',
    incompleteTitle: 'Incomplete details',
    incompleteText: 'Enter a place name and a clear address before saving.',
    saveFailed: 'Unable to save place',
    saveFailedText: 'Please try saving this place again.',
    removeTitle: 'Remove saved place?',
    removeText: 'This place will no longer appear when booking.',
    keep: 'Keep',
    remove: 'Remove',
  },
  policies: {
    title: 'Policies',
    subtitle: 'Review the terms and privacy information for DoorDrop.',
    heroTitle: 'Policies and protection',
    heroText: 'Open the legal and privacy pages below to understand how DoorDrop handles deliveries and account information.',
    terms: 'Terms and conditions',
    termsSub: 'Read the customer terms for bookings, cancellations and deliveries',
    privacy: 'Privacy policy',
    privacySub: 'See how DoorDrop stores and uses personal information',
  },
  forgot: {
    title: 'Forgot password',
    subtitle: 'Enter the email address linked to your DoorDrop account and we will send reset instructions.',
    empty: 'Enter the email address linked to your DoorDrop account.',
    invalid: 'Use a valid email address to send the reset instructions.',
    willSend: 'We will send the reset instructions to {email}.',
    sent: 'Password reset email sent. Check your inbox and spam folder.',
    failed: 'Unable to send the reset email right now. Please try again.',
    submit: 'Send reset email',
    back: 'Back to sign in',
  },
  splash: {
    tagline: 'Send. Track. Deliver.',
  },
  parcel: {
    title: 'Send parcel',
    inCity: 'In city',
    outsideCity: 'Other regions',
    pickupPlaceholder: 'Pickup location',
    dropoffPlaceholder: 'Where to?',
    searching: 'Searching...',
    pickOnMap: 'Pick on map',
    hideMap: 'Hide map',
    mapUnavailable: 'Map is unavailable. Search the destination instead.',
    destinationCity: 'City',
    busStand: 'Bus stand',
    weight: 'Weight (kg)',
    parcel: 'Parcel',
    motorcycle: 'Motorcycle delivery',
    recipient: 'Who receives it?',
    recipientName: 'Recipient name',
    chooseContacts: 'Contacts',
    hideContacts: 'Hide contacts',
    searchContacts: 'Search contacts',
    noContacts: 'No matching contacts.',
    calculating: 'Calculating fare...',
    notifyRecipient: 'Notify recipient by SMS',
    completeTitle: 'Complete order details',
    detecting: 'Finding your location...',
    nextPickup: 'Choose pickup',
    nextDropoff: 'Enter destination',
    nextCity: 'Choose city',
    nextStand: 'Choose bus stand',
    nextWeight: 'Enter weight',
    nextRecipient: 'Add recipient',
  },
  cargo: {
    book: 'Book cargo',
    details: 'Cargo details',
    carrier: 'Choose carrier',
    route: 'Route',
    pickup: 'Pickup',
    dropoff: 'Drop-off',
    hide: 'Hide',
    pickupPlaceholder: 'Start typing pickup location',
  },
  confirm: {
    title: 'Confirm',
    service: 'Service',
    payment: 'Payment',
    cash: 'Cash',
    when: 'When',
    fare: 'Fare',
    creating: 'Creating order...',
    confirm: 'Confirm',
    loginToComplete: 'Login to complete',
    authHint: 'Login or register to send this request.',
    notifyTitle: 'Notify recipient?',
    notifyMessage: 'Send an SMS to {phone} with this order and tracking details.',
    sendSms: 'Send SMS',
  },
  track: {
    title: 'Track',
    emptyTitle: 'No active order',
    emptyText: 'Open an order from history to track it.',
    findingDriver: 'Finding a driver',
    waitingDriver: 'Waiting for a nearby driver',
    assigned: 'Assigned',
    call: 'Call',
    noPhone: 'No phone',
    share: 'Share',
    smsRecipient: 'SMS recipient',
    rating: 'Rating',
    edit: 'Edit',
    rate: 'Rate',
    chat: 'Chat',
    noMessages: 'No messages yet.',
    chatAfterDriver: 'Chat opens after a driver is assigned.',
    message: 'Message',
    chatUnavailable: 'Chat unavailable',
    cancelled: 'Cancelled',
    orderPlaced: 'Order placed',
    lookingDriver: "We're looking for a nearby driver.",
    notifyPrompt: 'Send an SMS to {phone} with this order and tracking details.',
    sendSms: 'Send SMS',
    headingPickup: 'Heading to pickup',
    atPickup: 'Driver at pickup',
    onTheWay: 'On the way',
    statusDelivered: 'Delivered',
    stepReceived: 'Received',
    stepDriver: 'Driver',
    stepTransit: 'On the way',
    stepDelivered: 'Done',
    cancelOrder: 'Cancel order',
    cancelTitle: 'Cancel this order?',
    cancelHint: 'Tap a reason to cancel now.',
    keepOrder: 'Keep order',
    confirmCancel: 'Cancel order',
    cancelling: 'Cancelling...',
    cancelReasonRequired: 'Choose a reason first.',
    lookingText: "We're matching you with a nearby rider.",
    driverFound: 'Driver found',
    driverFoundText: '{name} is heading to your pickup.',
    driverFoundFallback: 'Your driver is heading to pickup.',
    cancelReasons: [
      'Wrong pickup or drop-off',
      'The fare is too high',
      'I no longer need this',
      'I want a different vehicle',
      'Pickup is taking too long',
    ],
    mapPreview: 'Route preview',
    arrivesIn: 'Arrives in {eta}',
    etaPickup: 'to pickup',
    etaDropoff: 'to drop-off',
  },
  history: {
    sendAgain: 'Send again',
  },
  profile: {
    title: 'Edit profile',
  },
  password: {
    title: 'Change password',
  },
} as const;

const sw: typeof en = {
  nav: {
    home: 'Nyumbani',
    track: 'Fuatilia',
    history: 'Historia',
    account: 'Akaunti',
  },
  common: {
    continue: 'Endelea',
    from: 'Kutoka',
    to: 'Kwenda',
    change: 'Badilisha',
    login: 'Ingia',
    register: 'Jisajili',
    loading: 'Inapakia...',
    save: 'Hifadhi',
    cancel: 'Ghairi',
    notNow: 'Si sasa',
    gotIt: 'Sawa',
  },
  notice: {
    offlineTitle: 'Huna mtandao',
    offlineText: 'Unganisha intaneti ili kutafuta maeneo na kuendelea.',
    locationTitle: 'Hatukuweza kupata sehemu hiyo',
    locationText: 'Jaribu jina la barabara, eneo, au alama ya karibu.',
    serviceTitle: 'Tafuta maeneo haipatikani kwa sasa',
    serviceText: 'Tafadhali jaribu tena baada ya sekunde chache.',
  },
  login: {
    title: 'Ingia',
    email: 'Barua pepe',
    password: 'Nenosiri',
    submit: 'Ingia',
    submitting: 'Inaingia...',
    missing: 'Weka barua pepe na nenosiri.',
    forgot: 'Umesahau nenosiri?',
    noAccount: 'Huna akaunti?',
    legal: 'Kwa kuendelea, unakubali',
    terms: 'Masharti',
  },
  register: {
    title: 'Jisajili',
    fullName: 'Jina kamili',
    email: 'Barua pepe',
    password: 'Nenosiri',
    confirmPassword: 'Thibitisha nenosiri',
    submit: 'Jisajili',
    submitting: 'Inaunda akaunti...',
    missing: 'Jaza jina, simu, barua pepe na nenosiri.',
    invalidPhone: 'Weka namba ya simu sahihi.',
    shortPassword: 'Nenosiri liwe na herufi 6 au zaidi.',
    mismatch: 'Nenosiri halifanani.',
    termsRequired: 'Kubali Masharti na Sera ya Faragha ili kuendelea.',
    agree: 'Ninakubali',
    terms: 'Masharti',
    and: 'na',
    privacy: 'Sera ya Faragha',
    haveAccount: 'Tayari una akaunti?',
  },
  menu: {
    title: 'Menyu',
    notSignedIn: 'Haujaingia',
    signOut: 'Toka',
    signOutFailed: 'Imeshindikana kutoka',
    tryAgain: 'Tafadhali jaribu tena.',
    account: 'Akaunti',
    savedPlaces: 'Maeneo yaliyohifadhiwa',
    notifications: 'Arifa',
    help: 'Msaada',
    policies: 'Sera',
  },
  help: {
    title: 'Msaada',
    intro: 'Piga simu au tuma ujumbe ukihitaji msaada wa oda.',
    call: 'Piga simu',
    whatsapp: 'WhatsApp',
    policies: 'Sera',
    callFailed: 'Imeshindikana kupiga',
    callHint: 'Tafadhali piga {phone} moja kwa moja.',
    whatsappFailed: 'Imeshindikana kufungua WhatsApp',
    whatsappHint: 'Tafadhali tuma ujumbe {phone} kwenye WhatsApp.',
  },
  notifications: {
    title: 'Arifa',
    enable: 'Washa arifa za oda',
    opening: 'Inafungua mipangilio...',
    emptyTitle: 'Hakuna arifa',
    emptyText: 'Taarifa za oda zitaonekana hapa.',
    updates: 'arifa',
    update: 'arifa',
    clearAll: 'Futa zote',
    deleting: 'Inafuta...',
  },
  savedPlaces: {
    title: 'Maeneo yaliyohifadhiwa',
    home: 'Nyumbani',
    office: 'Ofisi',
    shop: 'Duka',
    other: 'Nyingine',
    placeName: 'Jina la eneo',
    address: 'Anwani au alama',
    yourPlaces: 'Maeneo yako',
    empty: 'Bado huna maeneo yaliyohifadhiwa.',
    incompleteTitle: 'Taarifa hazijakamilika',
    incompleteText: 'Weka jina na anwani kabla ya kuhifadhi.',
    saveFailed: 'Imeshindikana kuhifadhi',
    saveFailedText: 'Tafadhali jaribu tena.',
    removeTitle: 'Ondoa eneo hili?',
    removeText: 'Halitaonekana tena unapoweka oda.',
    keep: 'Acha',
    remove: 'Ondoa',
  },
  policies: {
    title: 'Sera',
    subtitle: 'Soma masharti na faragha ya DoorDrop.',
    heroTitle: 'Sera na ulinzi',
    heroText: 'Fungua kurasa za kisheria na faragha ili kuelewa jinsi DoorDrop inavyoshughulikia oda na taarifa za akaunti.',
    terms: 'Masharti na vigezo',
    termsSub: 'Soma masharti ya kuweka oda, kufuta na uwasilishaji',
    privacy: 'Sera ya faragha',
    privacySub: 'Angalia jinsi DoorDrop inavyohifadhi na kutumia taarifa binafsi',
  },
  forgot: {
    title: 'Umesahau nenosiri',
    subtitle: 'Weka barua pepe ya akaunti yako ya DoorDrop tutakutumia maelekezo ya kubadilisha.',
    empty: 'Weka barua pepe iliyounganishwa na akaunti yako.',
    invalid: 'Tumia barua pepe sahihi kutuma maelekezo.',
    willSend: 'Tutapeleka maelekezo kwa {email}.',
    sent: 'Barua ya kubadilisha nenosiri imetumwa. Angalia inbox na spam.',
    failed: 'Imeshindikana kutuma barua sasa. Jaribu tena.',
    submit: 'Tuma barua',
    back: 'Rudi kuingia',
  },
  splash: {
    tagline: 'Tuma. Fuatilia. Fikisha.',
  },
  parcel: {
    title: 'Tuma parcel',
    inCity: 'Mjini',
    outsideCity: 'Mikoa mingine',
    pickupPlaceholder: 'Mahali pa kuchukua',
    dropoffPlaceholder: 'Tupeleke wapi?',
    searching: 'Inatafuta...',
    pickOnMap: 'Chagua kwenye ramani',
    hideMap: 'Ficha ramani',
    mapUnavailable: 'Ramani haipatikani. Tafuta sehemu ya kupeleka.',
    destinationCity: 'Mji',
    busStand: 'Stendi',
    weight: 'Uzito (kg)',
    parcel: 'Parcel',
    motorcycle: 'Usafiri wa pikipiki',
    recipient: 'Nani anapokea?',
    recipientName: 'Jina la mpokeaji',
    chooseContacts: 'Contacts',
    hideContacts: 'Ficha contacts',
    searchContacts: 'Tafuta contacts',
    noContacts: 'Hakuna contact inayofanana.',
    calculating: 'Inakokotoa nauli...',
    notifyRecipient: 'Mjulishe mpokeaji kwa SMS',
    completeTitle: 'Kamilisha taarifa za oda',
    detecting: 'Inatafuta eneo lako...',
    nextPickup: 'Chagua kuchukua',
    nextDropoff: 'Weka unakoenda',
    nextCity: 'Chagua mji',
    nextStand: 'Chagua stendi',
    nextWeight: 'Weka uzito',
    nextRecipient: 'Weka mpokeaji',
  },
  cargo: {
    book: 'Book cargo',
    details: 'Maelezo ya mzigo',
    carrier: 'Chagua gari',
    route: 'Njia',
    pickup: 'Kuchukua',
    dropoff: 'Kupeleka',
    hide: 'Ficha',
    pickupPlaceholder: 'Andika mahali pa kuchukua',
  },
  confirm: {
    title: 'Thibitisha',
    service: 'Huduma',
    payment: 'Malipo',
    cash: 'Taslimu',
    when: 'Wakati',
    fare: 'Nauli',
    creating: 'Inaunda oda...',
    confirm: 'Thibitisha',
    loginToComplete: 'Ingia kukamilisha',
    authHint: 'Ingia au jisajili kutuma ombi hili.',
    notifyTitle: 'Mjulishe mpokeaji?',
    notifyMessage: 'Tuma SMS kwa {phone} yenye namba ya oda na maelezo ya kufuatilia.',
    sendSms: 'Tuma SMS',
  },
  track: {
    title: 'Fuatilia',
    emptyTitle: 'Hakuna oda inayoendelea',
    emptyText: 'Fungua oda kutoka Historia kuifuata.',
    findingDriver: 'Inatafuta dereva',
    waitingDriver: 'Inasubiri dereva wa karibu',
    assigned: 'Amepangiwa',
    call: 'Piga',
    noPhone: 'Hakuna simu',
    share: 'Share',
    smsRecipient: 'SMS mpokeaji',
    rating: 'Kipimo',
    edit: 'Hariri',
    rate: 'Pima',
    chat: 'Chat',
    noMessages: 'Bado hakuna ujumbe.',
    chatAfterDriver: 'Chat inafunguka dereva akipangwa.',
    message: 'Ujumbe',
    chatUnavailable: 'Chat haipatikani',
    cancelled: 'Imefutwa',
    orderPlaced: 'Oda imewekwa',
    lookingDriver: 'Tunatafuta dereva wa karibu.',
    notifyPrompt: 'Tuma SMS kwa {phone} yenye maelezo ya kufuatilia.',
    sendSms: 'Tuma SMS',
    headingPickup: 'Anaelekea pickup',
    atPickup: 'Dereva yuko pickup',
    onTheWay: 'Njiani',
    statusDelivered: 'Imefika',
    stepReceived: 'Imepokelewa',
    stepDriver: 'Dereva',
    stepTransit: 'Njiani',
    stepDelivered: 'Imeisha',
    cancelOrder: 'Ghairi oda',
    cancelTitle: 'Ghairi oda hii?',
    cancelHint: 'Gusa sababu ili kughairi sasa.',
    keepOrder: 'Endelea na oda',
    confirmCancel: 'Ghairi oda',
    cancelling: 'Inaghairi...',
    cancelReasonRequired: 'Chagua sababu kwanza.',
    lookingText: 'Tunatafuta dereva wa karibu kwa ajili yako.',
    driverFound: 'Dereva amepatikana',
    driverFoundText: '{name} anaelekea pickup yako.',
    driverFoundFallback: 'Dereva wako anaelekea pickup.',
    cancelReasons: [
      'Pickup au drop-off si sahihi',
      'Nauli ni kubwa',
      'Sihitaji tena delivery hii',
      'Nataka gari tofauti',
      'Pickup inachukua muda',
    ],
    mapPreview: 'Muonekano wa njia',
    arrivesIn: 'Afika baada ya {eta}',
    etaPickup: 'kufika pickup',
    etaDropoff: 'kufika',
  },
  history: {
    sendAgain: 'Tuma tena',
  },
  profile: {
    title: 'Hariri wasifu',
  },
  password: {
    title: 'Badilisha nenosiri',
  },
};

export type AppCopy = typeof en;

export function useAppCopy(): AppCopy {
  const { language } = useLanguage();
  return language === 'sw' ? sw : en;
}
